GET http://localhost:3000/api/clientes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiI2MDYwYzgyNDk1YjU2YTM4NmNjOGU2NmEiLCJjYWR1Y2EiOjE2MTg3MjcxMDksImlhdCI6MTYxNzg2MzEwOX0.maxJbaNFtARvAxHg8THPgXe6qEtXtP-3di57niL6eXo

###
GET http://localhost:3000/api/teachers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiI2MDYwYzgyNDk1YjU2YTM4NmNjOGU2NmEiLCJjYWR1Y2EiOjE2MTg3MjcxMDksImlhdCI6MTYxNzg2MzEwOX0.maxJbaNFtARvAxHg8THPgXe6qEtXtP-3di57niL6eXo



###
POST http://localhost:3000/api/clientes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiI2MDYwYzgyNDk1YjU2YTM4NmNjOGU2NmEiLCJjYWR1Y2EiOjE2MTc4MjA1MzAsImlhdCI6MTYxNjk1NjUzMH0.IeAuV4Jbvfrg-mc-CEdzPPNxSaHorz3IuhwX4zdyhPk

{
    "nombre": "Francisco",
    "apellidos": "Garcia",
    "email": "fgarcia@gmail.com",
    "cuota": 11,
    "activo": true,
    "dni": "25874112Z"
}

###
POST http://localhost:3000/api/teachers
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiI2MDYwYzgyNDk1YjU2YTM4NmNjOGU2NmEiLCJjYWR1Y2EiOjE2MTc4MjA1MzAsImlhdCI6MTYxNjk1NjUzMH0.IeAuV4Jbvfrg-mc-CEdzPPNxSaHorz3IuhwX4zdyhPk

{
    "nombre": "Pilar",
    "apellidos": "Perez",
    "edad": 25,
    "especialidad": "Historia"
}

###
PUT http://localhost:3000/api/clientes/604bf7059c7167039825381c
Content-Type: application/json

{
    "nombre" : "Ana",
    "apellidos" : "González",
    "email" : "anagon@gmail.com",
    "cuota" : 20,
    "activo" : true
}

###
PUT http://localhost:3000/api/teachers/6060c42c86f92c26ec0636ab
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiI2MDYwNWMwYzIzMDBmYjI5ODgzYTllOTIiLCJjYWR1Y2EiOjE2MTc3OTE4NTQsImlhdCI6MTYxNjkyNzg1NH0.ZrvplFPa1rFbgMSLZXrqlH-Xnfe4M5Z6DiW1pNQui64

{
   "nombre": "Pilar",
    "apellidos": "Perez",
    "edad": 35,
    "especialidad": "Historia"
}

###
DELETE http://localhost:3000/api/clientes/604bf7059c7167039825381c


###
DELETE http://localhost:3000/api/teachers/6060b8cc1a7085154c7617ea
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiI2MDYwYzgyNDk1YjU2YTM4NmNjOGU2NmEiLCJjYWR1Y2EiOjE2MTc4MjA1MzAsImlhdCI6MTYxNjk1NjUzMH0.IeAuV4Jbvfrg-mc-CEdzPPNxSaHorz3IuhwX4zdyhPk

###
POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

{
    "username": "Cristina",
    "email": "cristina@gmail.com",
    "password": "holaMundo4321",
    "rol": "ADMIN"
}

###
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "email": "cristina@gmail.com",
    "password": "holaMundo4321"
}